### ISSUE TITLE
Internal Build #1 Bugs

### ISSUE THREAD

**Issue by aklinker1** [anime-skip/player#45]
All testing was done in Firefox while setting up the timestamps for `No Game, No Life`.

- [x] skip sections `duration diff * SPEED` seconds early
- [x] Add button isn't big enough
- [x] Override VRV Shortcuts
- [x] tab url watcher not working
- [x] filter button is gone
- [x] Edit episode drop down style
- [x] Absolute number doesn't show up all the time when all 3 values are entered
- [x] Refresh token flow fails
- [x] Update `.EpisodeInfo` base style:
    ```css
    element {
      max-width: 1100px;
      width: 75%;
      min-width: 400px;
    }
    ```
- [x] ~~Add refresh episode info button next to edit episode info button~~ **Not needed for now**
- [x] Loading beneath everything
- [x] Rework loading indicator logic
- [x] Current timestamp is decimal after the video changes
